/*
 * Documentation Generator
 * 
 * This component may not be reversed engineered for hacking or abuse
 * of The EGT Universe, The Universe, or third-party apps.
 * 
 * Justin K Kazmierczak
 * 
 * May be subject to The Universe Terms of Service.
 */

var jsdoc2md = require('jsdoc-to-markdown');
var docs = "";

//for each .js file in src
const fs = require('fs');
const files = fs.readdirSync('src');
for (const file of files) {
    if (file.endsWith('.js')) {

        docs += `# ${file}`;

        //get the contents of the first comment block in the script
        //and add it to the docs string
        var intro = fs.readFileSync(`src/${file}`, 'utf8').match(/\/\*\*([\s\S]*?)\*\//)[1];

        //remove the first 2 characters of each line in the intro if the characters - " *" only at the top of a line
        intro = intro.replace(/\n \*/g, "\n");

        //trim each line in the intro
        intro = intro.split("\n").map(line => line.trim()).join("\n");

        docs += intro + "\n";

        //append the docs generated by jsdoc2md
        docs += jsdoc2md.renderSync({ 
            files: `src/${file}`,
            'heading-depth': 2
        }) + "\n";

    }
}

fs.writeFileSync('DOCS.md', docs);
